name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
    - run: mvn -B clean package --no-transfer-progress
    - uses: actions/upload-artifact@v4
      with:
        name: formscanner
        path: formscanner-distribution/target/formscanner-*/**